services:
    _defaults:
        public: true

    # Extensions
    Smile\HipaySyliusPlugin\Payum\Extension\ClearPaymentContextExtension:
        class: Smile\HipaySyliusPlugin\Payum\Extension\ClearPaymentContextExtension
        arguments:
            - '@Smile\HipaySyliusPlugin\Context\PaymentContext'
        tags:
            - { name: payum.extension, factory: hipay_card }
            - { name: payum.extension, factory: hipay_moto_card }
            - { name: payum.extension, factory: hipay_oney3 }
            - { name: payum.extension, factory: hipay_oney4 }

    # Actions
    Smile\HipaySyliusPlugin\Payum\Action\StatusAction:
        class: Smile\HipaySyliusPlugin\Payum\Action\StatusAction
        arguments:
            - '@Smile\HipaySyliusPlugin\Security\HipaySignatureVerification'
        tags:
            - { name: payum.action, factory: hipay_card, alias: payum.action.status }
            - { name: payum.action, factory: hipay_moto_card, alias: payum.action.status }
            - { name: payum.action, factory: hipay_oney3, alias: payum.action.status }
            - { name: payum.action, factory: hipay_oney4, alias: payum.action.status }

    Smile\HipaySyliusPlugin\Payum\Action\NotifyAction:
        class: Smile\HipaySyliusPlugin\Payum\Action\NotifyAction
        arguments:
            - '@Smile\HipaySyliusPlugin\Security\HipaySignatureVerification'
        tags:
            - { name: payum.action, factory: hipay_card, alias: payum.action.notify }
            - { name: payum.action, factory: hipay_moto_card, alias: payum.action.notify }
            - { name: payum.action, factory: hipay_oney3, alias: payum.action.notify }
            - { name: payum.action, factory: hipay_oney4, alias: payum.action.notify }

    Smile\HipaySyliusPlugin\Payum\Action\CaptureAction:
        class: Smile\HipaySyliusPlugin\Payum\Action\CaptureAction
        arguments:
            - '@Smile\HipaySyliusPlugin\Api\CreateTransaction'
            - '@Smile\HipaySyliusPlugin\Factory\NotifyTokenFactory'
            - "@monolog.logger"
        tags:
            - { name: payum.action, factory: hipay_card, alias: payum.action.capture }
            - { name: payum.action, factory: hipay_moto_card, alias: payum.action.capture }
            - { name: payum.action, factory: hipay_oney3, alias: payum.action.capture }
            - { name: payum.action, factory: hipay_oney4, alias: payum.action.capture }

    Smile\HipaySyliusPlugin\Payum\Action\ResolveNextRouteAction:
        class: Smile\HipaySyliusPlugin\Payum\Action\ResolveNextRouteAction
        tags:
            - { name: payum.action, factory: hipay_card, alias: sylius.resolve_next_route }
            - { name: payum.action, factory: hipay_moto_card, alias: sylius.resolve_next_route }
            - { name: payum.action, factory: hipay_oney3, alias: sylius.resolve_next_route }
            - { name: payum.action, factory: hipay_oney4, alias: sylius.resolve_next_route }
