Sylius\Component\Customer\Model\Customer:
    properties:
        birthday:
            - NotBlank: # @todo Make YY -18 verification
                  message: smile_hipay_sylius_plugin.validation.customer.birthday.not_blank
                  groups: [hipay]
        phoneNumber:
            - NotBlank:
                  message: smile_hipay_sylius_plugin.validation.customer.phoneNumber.not_blank
                  groups: [hipay]
