Sylius\Component\Customer\Model\Customer:
    properties:
        birthday:
            - NotBlank:
                  message: smile_hipay_sylius_plugin.customer.birthday.not_blank
                  groups: [hipay]
            - LessThanOrEqual:
                  value: -18 years
                  message: smile_hipay_sylius_plugin.customer.birthday.underage
                  groups: [hipay]

        phoneNumber:
            - NotBlank:
                  message: smile_hipay_sylius_plugin.customer.phoneNumber.not_blank
                  groups: [hipay]
            - Regex:
                  pattern: |
                      /^
                        (?:(?:\+|00)33|0)     # Dialing code
                        \s*[1-9]              # First number (from 1 to 9)
                        (?:[\s.-]*\d{2}){4}   # End of the phone number
                        $/x
                  match: true
                  message: smile_hipay_sylius_plugin.customer.phoneNumber.regexp
                  groups: [hipay]
