Sylius\Component\Customer\Model\Customer:
    properties:
        birthday:
            - NotBlank: # @todo Make YY -18 verification
                  message: smile_hipay_sylius_plugin.customer.birthday.not_blank
                  groups: [hipay]
            - LessThanOrEqual:
                  value: -18 years
                  message: smile_hipay_sylius_plugin.customer.birthday.underage
                  groups: [hipay]

        phoneNumber:
            - NotBlank:
                  message: smile_hipay_sylius_plugin.customer.phoneNumber.not_blank
                  groups: [hipay]
